const T = 'https://image.tmdb.org/t/p/';
const P = `${T}w500`;
const B = `${T}w1280`;
const A = `${T}w185`;

export const MOVIES = [
  {
    id: 'rrr',
    title: 'RRR',
    language: 'Telugu',
    genre: 'Action',
    rating: 8.0,
    posterUrl: `${P}/lzjbBf0hxjZZ3WmRs5BKDK0fBrK.jpg`,
    bannerUrl: `${B}/wFjMtEyCQK2hBk9GfB0I0xqKOdL.jpg`,
    synopsis: 'Two revolutionaries forge an unlikely friendship and fight the British Raj in this epic spectacle.',
    cast: [
      { name: 'N. T. Rama Rao Jr.', imageUrl: `${A}/4q667iD5e0V0I077k5XsvvCeui8.jpg` },
      { name: 'Ram Charan', imageUrl: `${A}/kqjL19iscUc8wozWKoO7ss68ejZ.jpg` },
      { name: 'Alia Bhatt', imageUrl: `${A}/1U00WfFg4uW0dw0uIINFxFaJRPK.jpg` },
    ],
  },
  {
    id: 'vikram',
    title: 'Vikram',
    language: 'Tamil',
    genre: 'Action',
    rating: 8.3,
    posterUrl: `${P}/774UV1doUkGNOQz0T4HYgswPSuw.jpg`,
    bannerUrl: `${B}/9PCj1K2qDOnyW1BfpqqBVOejuPG.jpg`,
    synopsis: 'A black-ops squad and an ex-cop cross paths with a ruthless drug syndicate in Chennai.',
    cast: [
      { name: 'Kamal Haasan', imageUrl: `${A}/9I1D46bh91XjsOTUgHuboBH6asP.jpg` },
      { name: 'Vijay Sethupathi', imageUrl: `${A}/mCEObPV6adC97iPGu1hn4F4HGx1.jpg` },
      { name: 'Fahadh Faasil', imageUrl: `${A}/dW7U5F3NzvwhEiPfJP9i1AkiIqd.jpg` },
    ],
  },
  {
    id: 'jawan',
    title: 'Jawan',
    language: 'Hindi',
    genre: 'Thriller',
    rating: 7.2,
    posterUrl: `${P}/jFtBLgWf3xRL9vzwj3WxSCwTnz3.jpg`,
    bannerUrl: `${B}/fOsamTFjY6yvDH1GSU4Q7sMN0mY.jpg`,
    synopsis: 'A vigilante driven by a personal vendetta exposes corruption and delivers justice.',
    cast: [
      { name: 'Shah Rukh Khan', imageUrl: `${A}/vYBMPdYBdDP6gsVGFjaSir5TLnl.jpg` },
      { name: 'Nayanthara', imageUrl: `${A}/1EYfBd6HfujV5EBs4L6nwxWvx5d.jpg` },
      { name: 'Vijay Sethupathi', imageUrl: `${A}/mCEObPV6adC97iPGu1hn4F4HGx1.jpg` },
    ],
  },
  {
    id: 'premam',
    title: 'Premam',
    language: 'Malayalam',
    genre: 'Romance',
    rating: 8.3,
    posterUrl: `${P}/7bAtBUQRC1M4zaIlihesBPTAJ8a.jpg`,
    bannerUrl: `${B}/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg`,
    synopsis: 'George’s journey through love across school, college, and adulthood in Kerala.',
    cast: [
      { name: 'Nivin Pauly', imageUrl: `${A}/hJBqvxfxWaWiYRjkEO8w2RJYI97.jpg` },
      { name: 'Sai Pallavi', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
      { name: 'Madonna Sebastian', imageUrl: `${A}/kYv98BErj9YOCZuqmFCGbvRSGSz.jpg` },
    ],
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    language: 'English',
    genre: 'Drama',
    rating: 8.4,
    posterUrl: `${P}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`,
    bannerUrl: `${B}/cUIqZd6jJCbO94Txt1CkTs7MSeP.jpg`,
    synopsis: 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.',
    cast: [
      { name: 'Cillian Murphy', imageUrl: `${A}/llkbyWKwpfowZ6C8peBjIV9jj99.jpg` },
      { name: 'Emily Blunt', imageUrl: `${A}/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg` },
      { name: 'Robert Downey Jr.', imageUrl: `${A}/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg` },
    ],
  },
  {
    id: 'leo',
    title: 'Leo',
    language: 'Tamil',
    genre: 'Action',
    rating: 7.2,
    posterUrl: `${P}/jXiszPlTVqyl1ys3CiTAelSOJSO.jpg`,
    bannerUrl: `${B}/jXiszPlTVqyl1ys3CiTAelSOJSO.jpg`,
    synopsis: 'A café owner in Kashmir is pulled back into a violent past he tried to leave behind.',
    cast: [
      { name: 'Vijay', imageUrl: `${A}/zjfollRevSMSdABOxBbkOXXdYzQ.jpg` },
      { name: 'Trisha Krishnan', imageUrl: `${A}/zqFGjGTFjTdT9VzGkpDjUkBdVwe.jpg` },
      { name: 'Sanjay Dutt', imageUrl: `${A}/ksCb8GAxaAQIyYxBOAn6POYJCAr.jpg` },
    ],
  },
  {
    id: 'animal',
    title: 'Animal',
    language: 'Hindi',
    genre: 'Crime',
    rating: 6.1,
    posterUrl: `${P}/kfPlCDMsYFMKmf61blVRNGv3iPZ.jpg`,
    bannerUrl: `${B}/kfPlCDMsYFMKmf61blVRNGv3iPZ.jpg`,
    synopsis: 'A son’s obsessive love for his father spirals into a brutal underworld conflict.',
    cast: [
      { name: 'Ranbir Kapoor', imageUrl: `${A}/6SNS0S2ZTMYjKq6IFs6AYSKtvoR.jpg` },
      { name: 'Rashmika Mandanna', imageUrl: `${A}/kmUVToMDYtHlz572j5b5d9KRayu.jpg` },
      { name: 'Anil Kapoor', imageUrl: `${A}/se1XErGbRhh8XjXPiN0henRWOW9.jpg` },
    ],
  },
  {
    id: 'pathaan',
    title: 'Pathaan',
    language: 'Hindi',
    genre: 'Action',
    rating: 6.9,
    posterUrl: `${P}/3pzfxwVatFqFSXuD7VBWQyxCv1K.jpg`,
    bannerUrl: `${B}/3pzfxwVatFqFSXuD7VBWQyxCv1K.jpg`,
    synopsis: 'An exiled RAW agent returns to stop a terror outfit from striking India.',
    cast: [
      { name: 'Shah Rukh Khan', imageUrl: `${A}/vYBMPdYBdDP6gsVGFjaSir5TLnl.jpg` },
      { name: 'Deepika Padukone', imageUrl: `${A}/soViIVOTYw7QXMR9J8tXSYAkJp.jpg` },
      { name: 'John Abraham', imageUrl: `${A}/lCySuYjhXix3FzQdS4oceDDrXKI.jpg` },
    ],
  },
  {
    id: 'sita-ramam',
    title: 'Sita Ramam',
    language: 'Telugu',
    genre: 'Romance',
    rating: 8.6,
    posterUrl: `${P}/bSqtVRhyS29nHXoD1dLWOGPZ0OK.jpg`,
    bannerUrl: `${B}/bSqtVRhyS29nHXoD1dLWOGPZ0OK.jpg`,
    synopsis: 'A love story between an army officer and a princess, told across letters and time.',
    cast: [
      { name: 'Dulquer Salmaan', imageUrl: `${A}/dW7U5F3NzvwhEiPfJP9i1AkiIqd.jpg` },
      { name: 'Mrunal Thakur', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
      { name: 'Rashmika Mandanna', imageUrl: `${A}/1U00WfFg4uW0dw0uIINFxFaJRPK.jpg` },
    ],
  },
  {
    id: 'ps1',
    title: 'Ponniyin Selvan: Part I',
    language: 'Tamil',
    genre: 'Epic',
    rating: 7.7,
    posterUrl: `${P}/nCbkOy07TE7vpLW0dCADSZ1ThDy.jpg`,
    bannerUrl: `${B}/nCbkOy07TE7vpLW0dCADSZ1ThDy.jpg`,
    synopsis: 'Vandiyathevan crosses a empire in turmoil as succession and conspiracy unfold.',
    cast: [
      { name: 'Karthi', imageUrl: `${A}/kqjL19iscUc8wozWKoO7ss68ejZ.jpg` },
      { name: 'Aishwarya Rai Bachchan', imageUrl: `${A}/1U00WfFg4uW0dw0uIINFxFaJRPK.jpg` },
      { name: 'Vikram', imageUrl: `${A}/9I1D46bh91XjsOTUgHuboBH6asP.jpg` },
    ],
  },
  {
    id: 'minnal-murali',
    title: 'Minnal Murali',
    language: 'Malayalam',
    genre: 'Superhero',
    rating: 8.0,
    posterUrl: `${P}/ApGBQnPJXMZvqlPwv0QfxVjH3oI.jpg`,
    bannerUrl: `${B}/ApGBQnPJXMZvqlPwv0QfxVjH3oI.jpg`,
    synopsis: 'A tailor gains lightning powers and must become the hero his village needs.',
    cast: [
      { name: 'Tovino Thomas', imageUrl: `${A}/hJBqvxfxWaWiYRjkEO8w2RJYI97.jpg` },
      { name: 'Guru Somasundaram', imageUrl: `${A}/mCEObPV6adC97iPGu1hn4F4HGx1.jpg` },
      { name: 'Aju Varghese', imageUrl: `${A}/dW7U5F3NzvwhEiPfJP9i1AkiIqd.jpg` },
    ],
  },
  {
    id: 'master',
    title: 'Master',
    language: 'Tamil',
    genre: 'Action',
    rating: 7.3,
    posterUrl: `${P}/qhlzxupP4fMnHNoWE5YqhN8xK6V.jpg`,
    bannerUrl: `${B}/qhlzxupP4fMnHNoWE5YqhN8xK6V.jpg`,
    synopsis: 'An alcoholic professor locks horns with a juvenile crime boss at a reform school.',
    cast: [
      { name: 'Vijay', imageUrl: `${A}/zvPS8B0dPwfEIf3U5YNtWqvy9nN.jpg` },
      { name: 'Vijay Sethupathi', imageUrl: `${A}/mCEObPV6adC97iPGu1hn4F4HGx1.jpg` },
      { name: 'Malavika Mohanan', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
    ],
  },
  {
    id: 'top-gun',
    title: 'Top Gun: Maverick',
    language: 'English',
    genre: 'Action',
    rating: 8.2,
    posterUrl: `${P}/62HCnUSTgH3CQ9aBBWNcHVYMXyv.jpg`,
    bannerUrl: `${B}/62HCnUSTgH3CQ9aBBWNcHVYMXyv.jpg`,
    synopsis: 'Pete “Maverick” Mitchell trains a new generation of pilots for a dangerous mission.',
    cast: [
      { name: 'Tom Cruise', imageUrl: `${A}/us9yQaNUPtp8m8HFodYJXS6X8pP.jpg` },
      { name: 'Miles Teller', imageUrl: `${A}/aciu7YM8fD0BzrrA6cJ5wDKZIA6.jpg` },
      { name: 'Jennifer Connelly', imageUrl: `${A}/wdmcJagSRJ65AuJ4IUCzuHAdvgy.jpg` },
    ],
  },
  {
    id: 'barbie',
    title: 'Barbie',
    language: 'English',
    genre: 'Comedy',
    rating: 6.9,
    posterUrl: `${P}/iuFNMS8XAp3Wkd2zqPcrX325mcz.jpg`,
    bannerUrl: `${B}/iuFNMS8XAp3Wkd2zqPcrX325mcz.jpg`,
    synopsis: 'Barbie leaves Barbieland to discover the real world—and what it means to be human.',
    cast: [
      { name: 'Margot Robbie', imageUrl: `${A}/1U00WfFg4uW0dw0uIINFxFaJRPK.jpg` },
      { name: 'Ryan Gosling', imageUrl: `${A}/kqjL19iscUc8wozWKoO7ss68ejZ.jpg` },
      { name: 'America Ferrera', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
    ],
  },
  {
    id: 'brahmastra',
    title: 'Brahmāstra: Part One – Shiva',
    language: 'Hindi',
    genre: 'Fantasy',
    rating: 5.6,
    posterUrl: `${P}/6JqzCd6GyZm0FHNYNP7bCNZ1xZk.jpg`,
    bannerUrl: `${B}/6JqzCd6GyZm0FHNYNP7bCNZ1xZk.jpg`,
    synopsis: 'A young man discovers a connection to a secret society guarding astral weapons.',
    cast: [
      { name: 'Ranbir Kapoor', imageUrl: `${A}/6SNS0S2ZTMYjKq6IFs6AYSKtvoR.jpg` },
      { name: 'Alia Bhatt', imageUrl: `${A}/1U00WfFg4uW0dw0uIINFxFaJRPK.jpg` },
      { name: 'Amitabh Bachchan', imageUrl: `${A}/9I1D46bh91XjsOTUgHuboBH6asP.jpg` },
    ],
  },
  {
    id: 'baahubali2',
    title: 'Baahubali 2: The Conclusion',
    language: 'Telugu',
    genre: 'Epic',
    rating: 8.2,
    posterUrl: `${P}/qsXFEH6Qv0TvbRVAYL4WpQwcXbf.jpg`,
    bannerUrl: `${B}/qsXFEH6Qv0TvbRVAYL4WpQwcXbf.jpg`,
    synopsis: 'Mahendra Baahubali’s son learns his legacy and confronts the tyrant Bhallaladeva.',
    cast: [
      { name: 'Prabhas', imageUrl: `${A}/kqjL19iscUc8wozWKoO7ss68ejZ.jpg` },
      { name: 'Anushka Shetty', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
      { name: 'Rana Daggubati', imageUrl: `${A}/4q667iD5e0V0I077k5XsvvCeui8.jpg` },
    ],
  },
  {
    id: 'bangalore-days',
    title: 'Bangalore Days',
    language: 'Malayalam',
    genre: 'Drama',
    rating: 8.3,
    posterUrl: `${P}/1FevzSkxlAYnu3fsU3NWJnUoWZP.jpg`,
    bannerUrl: `${B}/nUGgjaSQHIJwQOVJPyOury7BReU.jpg`,
    synopsis: 'Three cousins chase dreams and love in Bangalore in this feel-good ensemble tale.',
    cast: [
      { name: 'Dulquer Salmaan', imageUrl: `${A}/dW7U5F3NzvwhEiPfJP9i1AkiIqd.jpg` },
      { name: 'Nazriya Nazim', imageUrl: `${A}/kYv98BErj9YOCZuqmFCGbvRSGSz.jpg` },
      { name: 'Nivin Pauly', imageUrl: `${A}/hJBqvxfxWaWiYRjkEO8w2RJYI97.jpg` },
    ],
  },
  {
    id: 'drishyam',
    title: 'Drishyam',
    language: 'Malayalam',
    genre: 'Thriller',
    rating: 8.4,
    posterUrl: `${P}/wg6mP3YE1FWOHytAVwiyuGf1FMq.jpg`,
    bannerUrl: `${B}/iHBsSKDOkBxfMtPF0kVe3gqSM2G.jpg`,
    synopsis: 'A cable operator’s family faces police pressure after an unexpected tragedy.',
    cast: [
      { name: 'Mohanlal', imageUrl: `${A}/9I1D46bh91XjsOTUgHuboBH6asP.jpg` },
      { name: 'Meena', imageUrl: `${A}/1EYfBd6HfujV5EBs4L6nwxWvx5d.jpg` },
      { name: 'Ansiba Hassan', imageUrl: `${A}/yEF1Ugrftu7oUZ8ilnmCPR7O8mm.jpg` },
    ],
  },
  {
    id: 'dangal',
    title: 'Dangal',
    language: 'Hindi',
    genre: 'Sports',
    rating: 8.4,
    posterUrl: `${P}/svWxyNwWFP1NmgB6VVYv5FYYN.jpg`,
    bannerUrl: `${B}/svWxyNwWFP1NmgB6VVYv5FYYN.jpg`,
    synopsis: 'Former wrestler Mahavir trains his daughters to become India’s first female wrestling champions.',
    cast: [
      { name: 'Aamir Khan', imageUrl: `${A}/wbP0uKaeJYpRiGQOzl9G4fo0j6.jpg` },
      { name: 'Fatima Sana Shaikh', imageUrl: `${A}/eVOziSvi6PLL5vkROHO1sbsKUFW.jpg` },
      { name: 'Sanya Malhotra', imageUrl: `${A}/sQ0VIqGLecfpwYayO05Z7NC32yN.jpg` },
    ],
  },
  {
    id: 'arjun-reddy',
    title: 'Arjun Reddy',
    language: 'Telugu',
    genre: 'Romance',
    rating: 8.0,
    posterUrl: `${P}/oBfyUEtCG57U9qFWvq4c1SQEXI.jpg`,
    bannerUrl: `${B}/oBfyUEtCG57U9qFWvq4c1SQEXI.jpg`,
    synopsis: 'A brilliant surgeon spirals into self-destruction after his love story falls apart.',
    cast: [
      { name: 'Vijay Deverakonda', imageUrl: `${A}/8oVIWyIoFUal8SJFnmCUtkkm1HP.jpg` },
      { name: 'Shalini Pandey', imageUrl: `${A}/x0VLQqGuQocLALiauiZV2wge3OI.jpg` },
      { name: 'Rahul Ramakrishna', imageUrl: `${A}/mCEObPV6adC97iPGu1hn4F4HGx1.jpg` },
    ],
  },
];
